Usale/Controllers/VendaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Usale.DTO;
using Usale.Service;

namespace Usale.Controllers
{
    public class VendaController: Controller
    {

        private readonly IProdutoService _prodServ;
        private readonly ILojaService _lojaServ;

        public VendaController(IProdutoService prodServ, ILojaService lojaServ)
        {
            _prodServ = prodServ;
            _lojaServ = lojaServ;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VerLoja(int lojaId)
        {
            var loja = _lojaServ.GetLojaById(lojaId);
            ViewBag.Loja = loja;
            return View();
        }

        [HttpGet]
        public IActionResult VerProduto(int produtoId)
        {
            var produto = _prodServ.GetProdutoById(produtoId);
            var loja = _lojaServ.GetLojaByProdutoId(produtoId);
            ViewBag.Produto = produto;
            ViewBag.Loja = loja;
            return View();
        }



        [HttpGet]
        public List<ProdutoDTO> GetProdutos(string query)
        {
            return _prodServ.GetProdutosByNome(query);
        }

        [HttpGet]
        public List<LojaDTO> GetLojas(string query)
        {
            return _lojaServ.GetLojasByNome(query);
        }

        [HttpGet]
        public List<LojaDTO> GetIndexLojas()
        {
            return _lojaServ.GetIndexLojas();
        }




    }
}

Usale/Views/Venda/Index.cshtml
@{
    ViewData["Title"] = "Vendas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/style.css" />
<link rel="stylesheet" href="~/css/master.css" />

<!-- Vendor CSS Files -->
<link href="~/vendor/icofont/icofont.min.css" rel="stylesheet">
<link href="~/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
<link href="~/vendor/aos/aos.css" rel="stylesheet">
<link href="~/vendor/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


<main id="main">
    <div class="hero-section">

        <div class="wave">
            <svg width="100%" height="355px" viewBox="0 0 1920 355" version="1.1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink">
                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
                        <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,757 L1017.15166,757 L0,757 L0,439.134243 Z" id="Path"></path>
                    </g>
                </g>
            </svg>
        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 hero-text-image">

                    <div class="bg-light rounded pb-5" style="box-shadow: 1px 5px 10px #808080; height: 850px; overflow-y: scroll; overflow-x: hidden; margin-top: 100px;">

                        <div class="w-100 text-center">
                            <img src="~/img/logo-grande-escura.png" alt="U-Sale" width="300" />
                        </div>

                        <div class="modal-header text-center" style="border: none; margin-top: -80px;">
                            <h5 style="font-size: 30px; color: #1b6ec2" class="modal-title w-100">Os comércios locais lhes desejam boas compras!</h5>
                        </div>

                        <div class="w-100 ml-5 pl-5">
                            <input type="text" id="query" class="form-control" style="width: 85%;" placeholder="Insira o nome de um produto ou loja" />
                            <button id="btn-query" class="btn btn-primary" style="width: 85%; position: relative; border-radius: 0px 2px 2px 0px"><i class="fas fa-search"></i> Pesquisar</button>

                            <div class="form-check mt-1">
                                <input class="form-check-input" type="radio" name="tipo" id="produtos" value="produtos" checked>
                                <label class="form-check-label ml-1" for="produtos">
                                    produtos
                                </label>

                                <input class="form-check-input ml-4" type="radio" name="tipo" id="lojas" value="lojas">
                                <label class="form-check-label  ml-5" for="lojas">
                                    comércios
                                </label>
                            </div>
                        </div>

                        <div class="w-100" id="grid">
                            <div class="w-100" id="grid-removivel">

                            </div>
                        </div>


                    </div>


                </div>
            </div>
        </div>

    </div>





</main>


<script src="~/js/jquery-3.4.1-COMPLETASSO.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"></script>
<script src="~/vendor/sticky/sticky.js" type="text/javascript"></script>
<script src="~/vendor/owlcarousel/owl.carousel.js" type="text/javascript"></script>
<script src="~/vendor/aos/aos.js" type="text/javascript"></script>
<script src="~/vendor/easing/easing.js" type="text/javascript"></script>
<script src="~/js/main.js"></script>
<script src="~/js/jquery-funcoes.js"></script>

<script>

    $(document).ready(function () {


        function AtualizaCardsProdutos(produtos) {
            var divRemovivel = document.getElementById("grid-removivel");
            divRemovivel.innerHTML =
                `
                    <p style="font-size: 18px; text-align: center; width: 100%;" class="text-dark">
                        <i class="fa fa-spinner fa-spin" style="font-size: 24px"></i> Carregando Produtos ...
                    </p>
                `;

            var conteudo = '<div class="card-group ml-5 mr-5">';

            var formato = { minimumFractionDigits: 2, style: 'currency', currency: 'BRL' }

            produtos.forEach(p => {
                conteudo +=
                    `
                          <div class="m-2" style="width: 310px;">
                            <div style='background: url("${p.imagens[0].url}"); background-size: cover; width: 100%; height: 250px;'>
                            </div>
                            <div class="card-body">
                              <h5 class="card-title text-center">${p.nome}</h5>
                              <p class="card-text text-dark text-left" style="font-size: 15px;">${p.descricao}</p>
                              <p class="card-text text-dark text-right" style="font-size: 25px;">${p.preco.toLocaleString('pt-BR', formato)}</p>
                            </div>
                            <div class="card-footer">
                              <button class="btn btn-primary btn-ver-produto w-100" id="${p.produtoId}">Ver Produto</button>
                            </div>
                          </div>
                    `;
            });
            conteudo += "</div>";
            divRemovivel.innerHTML = conteudo;
        }


        function AtualizaCardsLojas(lojas) {
            var divRemovivel = document.getElementById("grid-removivel");
            divRemovivel.innerHTML =
                `
                    <p style="font-size: 18px; text-align: center; width: 100%;" class="text-dark">
                        <i class="fa fa-spinner fa-spin" style="font-size:24px"></i> Carregando Lojas ...
                    </p>
                `;

            var conteudo = '<div class="card-group ml-5 mr-5">';

            lojas.forEach(l => {
                conteudo +=
                    `
                          <div class="m-2" style="width: 310px;">
                            <div style='background: url("../../lojaslogo/${l.logo}"); background-size: cover; width: 100%; height: 250px;'>
                            </div>
                            <div class="card-body">
                              <h5 class="card-title text-center">${l.nome}</h5>
                              <p class="card-text text-dark text-left" style="font-size: 15px;">${l.endereco}</p>
                            </div>
                            <div class="card-footer">
                              <button class="btn btn-primary btn-ver-loja w-100" id="${l.lojaId}">Ver Loja</button>
                            </div>
                          </div>
                    `;
            });
            conteudo += "</div>";
            divRemovivel.innerHTML = conteudo;
        }



        $("#btn-query").click(function () {
            var tipo = $('input[name=tipo]:checked').val();

            if (tipo == "produtos") {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetProdutos", "Venda")",
                    data: {
                        query: $("#query").val(),
                    },
                    success: function (produtos) {
                        AtualizaCardsProdutos(produtos);

                        $(".btn-ver-produto").click(function () {
                            window.location.assign('@Url.Action("VerProduto","Venda")' + "?produtoId="+$(this).attr("id"));
                        });

                    },
                });
            }
            else {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetLojas", "Venda")",
                    data: {
                        query: $("#query").val(),
                        tipo: $("#tipo").val()
                    },
                    success: function (lojas) {
                        AtualizaCardsLojas(lojas);
                    },
                });
            }

        });


        $.ajax({
            type: "GET",
            url: "@Url.Action("GetIndexLojas", "Venda")",
            data: {},
            success: function (lojas) {
                AtualizaCardsLojas(lojas);

                $(".btn-ver-loja").click(function () {
                    window.location.assign('@Url.Action("VerLoja","Venda")' + "?lojaId="+$(this).attr("id"));
                });


            },
        });

    });

</script>

Usale/Views/Venda/VerLoja.cshtml
@{
    ViewData["Title"] = "VerLoja";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var loja = ViewBag.Loja;
}

<link rel="stylesheet" href="~/css/style.css" />
<link rel="stylesheet" href="~/css/master.css" />

<!-- Vendor CSS Files -->
<link href="~/vendor/icofont/icofont.min.css" rel="stylesheet">
<link href="~/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
<link href="~/vendor/aos/aos.css" rel="stylesheet">
<link href="~/vendor/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


<main id="main">
    <div class="hero-section">

        <div class="wave">
            <svg width="100%" height="355px" viewBox="0 0 1920 355" version="1.1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink">
                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
                        <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,757 L1017.15166,757 L0,757 L0,439.134243 Z" id="Path"></path>
                    </g>
                </g>
            </svg>
        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 hero-text-image">

                    <div class="bg-light rounded pb-5" style="box-shadow: 1px 5px 10px #808080; height: 850px; overflow-y: scroll; overflow-x: hidden; margin-top: 100px;">

                        <div style="width: 100%; height: 450px; background: url('@(loja.Banner)'); background-size: cover; background-position: center; position: relative; top: -100px;">

                            <div style="width: 200px; height: 200px; background: url('../../lojaslogo/@(loja.Logo)'); background-size: cover; background-position: center; position: relative; top: 350px; border-radius: 50%; border: 2px #fff solid; z-index: 200; margin: 100px;">

                            </div>

                        </div>
                        <div class="w-100">
                            <h1 class="text-center text-dark border-bottom border-dark">@(loja.Nome)</h1>
                        </div>

                        <div class="w-100" id="grid">
                            <div class="w-100" id="grid-removivel">
                                <div class="card-group ml-5 mr-5">

                                    @foreach (var p in loja.Produtos)
                                    {
                                        <div class="m-2" style="width: 310px;">
                                            <div style='background: url("@(p.Imagens[0].URL)"); background-size: cover; width: 100%; height: 250px;'>
                                            </div>
                                            <div class="card-body">
                                                <h5 class="card-title text-center">@(p.Nome)</h5>
                                                <p class="card-text text-dark text-left" style="font-size: 15px;">@(p.Descricao)</p>
                                                <p class="card-text text-dark text-right" style="font-size: 25px;">@(p.Preco)</p>
                                            </div>
                                            <div class="card-footer">
                                                <button class="btn btn-primary btn-ver-produto w-100" id="@(p.ProdutoId)">Ver Produto</button>
                                            </div>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div>


                    </div>


                </div>
            </div>
        </div>

    </div>





</main>


<script src="~/js/jquery-3.4.1-COMPLETASSO.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"></script>
<script src="~/vendor/sticky/sticky.js" type="text/javascript"></script>
<script src="~/vendor/owlcarousel/owl.carousel.js" type="text/javascript"></script>
<script src="~/vendor/aos/aos.js" type="text/javascript"></script>
<script src="~/vendor/easing/easing.js" type="text/javascript"></script>
<script src="~/js/main.js"></script>
<script src="~/js/jquery-funcoes.js"></script>

<script>

    $(document).ready(function () {

        $(".btn-ver-produto").click(function () {
            window.location.assign('@Url.Action("VerProduto","Venda")' + "?produtoId="+$(this).attr("id"));
        });

    });

</script>

Usale/Views/Venda/VerProduto.cshtml
@{
    ViewData["Title"] = "VerProduto";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var p = ViewBag.Produto;
    var l = ViewBag.Loja;
}



<link rel="stylesheet" href="~/css/style.css" />
<link rel="stylesheet" href="~/css/master.css" />

<!-- Vendor CSS Files -->
<link href="~/vendor/icofont/icofont.min.css" rel="stylesheet">
<link href="~/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
<link href="~/vendor/aos/aos.css" rel="stylesheet">
<link href="~/vendor/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


<main id="main">
    <div class="hero-section">

        <div class="wave">
            <svg width="100%" height="355px" viewBox="0 0 1920 355" version="1.1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink">
                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
                        <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,757 L1017.15166,757 L0,757 L0,439.134243 Z" id="Path"></path>
                    </g>
                </g>
            </svg>
        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 hero-text-image">

                    <div class="bg-light rounded pb-5" style="box-shadow: 1px 5px 10px #808080; height: 850px; overflow-y: scroll; overflow-x: hidden; margin-top: 100px;">

                        <div style="width: 100%; height: 450px; background: url('@(l.Banner)'); background-size: cover; background-position: center; position: relative; top: -100px;">

                            <div style="width: 200px; height: 200px; background: url('../../lojaslogo/@(l.Logo)'); background-size: cover; background-position: center; position: relative; top: 350px; border-radius: 50%; border: 2px #fff solid; z-index: 200; margin: 100px;">

                            </div>

                        </div>
                        <div class="w-100">
                            <h1 class="text-center text-dark border-bottom border-dark">@(l.Nome) - @(p.Nome)</h1>
                        </div>


                        <div class="w-50 float-left mt-">
                            @*CAROUSEL*@
                            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                                    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">

                                    @{
                                        var i = 0;
                                    }

                                    @foreach (var img in p.Imagens)
                                    {
                                        if (i == 0)
                                        {
                                            <div class="carousel-item active" style="height: 400px; width: 100%; background: url('@(img.URL)'); background-size: cover; background-position: center;"></div>
                                            <div class="carousel-caption d-none d-md-block" style="background: #138496dd; border-radius: 5px;">
                                                <h5 class="text-light">Descricao:</h5>
                                                <p>@(p.Descricao)</p>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="carousel-item" style="height: 400px; width: 100%; background: url('@(img.URL)'); background-size: cover; background-position: center;"></div>
                                        }
                                        i = i + 1;
                                    }
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>



                        </div>
                        <div class="w-50 float-right">
                            @*INFOS DO PRODUTO/VENDA/ENTREGA E BTN GETNET DE COMPRAR*@
                            <div>
                                <h2 class="text-dark text-right border-bottom mr-5">Preço: @(p.Preco.ToString("C"))</h2>
                            </div>
                            <div>
                                <br />
                                <h2 class="text-dark text-right border-bottom mr-5">Quantidade: @(p.UniMedida)</h2>
                                <input value="1" min="1" max="100" type="number" id="qtd-compra" class="form-control" style="width: 100px; right: -400px; position: relative;" />
                            </div>
                            <div>
                                <br />
                                <h2 class="text-dark text-right border-bottom mr-5">Entrega:</h2>
                                <select class="form-control" style="width: 200px; right: -300px; position: relative;">
                                    <option value="0">Escolha</option>
                                    <option value="1">Entrega Uber</option>
                                    <option value="2">Retirar na loja</option>
                                </select>
                            </div>

                            <div>
                                <br />
                                <button id="compra-btn" class="m-1 ml-5 pl-2 btn btn-lg" role="button" style="background: #ee1c25; width: 80%; padding: 10px; border-radius: 30px;">Comprar<i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i></button>

                            </div>

                        </div>

                    </div>


                </div>
            </div>
        </div>

    </div>





</main>


<script src="~/js/jquery-3.4.1-COMPLETASSO.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"></script>
<script src="~/vendor/sticky/sticky.js" type="text/javascript"></script>
<script src="~/vendor/owlcarousel/owl.carousel.js" type="text/javascript"></script>
<script src="~/vendor/aos/aos.js" type="text/javascript"></script>
<script src="~/vendor/easing/easing.js" type="text/javascript"></script>
<script src="~/js/main.js"></script>
<script src="~/js/jquery-funcoes.js"></script>

<script>

    $(document).ready(function () {

        $("#compra-btn").mouseover(function () {
            $("#compra-btn").css({
                "background": "#d41018",
                "color": "#fff"
            });
        });

    });

</script>