Usale/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Usale.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult QrCode()
        {
            return View();
        }


    }
}

Usale/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Usale.Areas.Identity.Data;
using Usale.DTO;
using Usale.Service;

namespace Usale.Controllers
{

    public class UserController: Controller
    {


        private readonly SignInManager<UsaleUser> _signInManager;
        private readonly UserManager<UsaleUser> _userManager;
        private readonly IUserService _serv;

        public UserController(SignInManager<UsaleUser> signInManager, UserManager<UsaleUser> userManager, IUserService serv)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _serv = serv;
        }

        [HttpGet]
        public IActionResult CadastroClienteView()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CadastroVendedorView()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ModalProdRegister()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ModalUserRegister()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CadastroVendedor([FromBody] VendedorDTO v)
        { 
            v.Loja.Produtos = null;
            await _serv.CadastroVendedor(v);

            /* SIGNINMANAGER */
            var u = new UsaleUser()
            {
                Email = v.Email,
                UserName = v.Email,
                EmailConfirmed = true,                
            };

            await _userManager.CreateAsync(u, v.Password);
            var uBD = _userManager.FindByNameAsync(u.Email);
            await _signInManager.SignInAsync(u,true, null);

            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> CadastroCliente([FromForm] ClienteDTO c)
        {
            await _serv.CadastroCliente(c);
            return View("Index", "HomeController");
        }

    }
}

Usale/Views/Shared/_Footer.cshtml
<footer class="container-fluid site-section cta-section" style="position: absolute; bottom: -320px;">
    <div class="row w-100">
        <div class="col-12 w-100">
            <div class="">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-12 mr-auto text-center text-md-left mb-5 mb-md-0">
                            <h2> Tenha muito mais controle sobre seu negócio.</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row"> 
                <div class="w-100 mt-5">
                    <p class="text-center text-light">
                        U-Sale &copy; 2020 - Todos os direitos reservados.
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>

Usale/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Usale.Areas.Identity.Data

@inject SignInManager<UsaleUser> SignInManager
@inject UserManager<UsaleUser> UserManager

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Usale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/master.css" />
    <link rel="icon" href="~/img/logo-pequenina.png" />

    <!-- Vendor CSS Files -->
    <link href="~/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <style>
        #minha-navbar-lateral {
            position: fixed;
            top: -1000px;
            width: 100%;
            height: auto;
            background-color: #fff;
            z-index: 999;
        }

        #listinha-meu-menu-lateral {
            z-index: 1000 !important;
            color: #fff !important;
        }
    </style>


</head>
<body>

    <div id="sticky-wrapper" class="sticky-wrapper" style="height: 92px;">
        <header class="site-navbar js-sticky-header site-navbar-target" style="color: rgb(0, 0, 0); width: 1440px;" role="banner">

            <div class="container pt-2">


                <div class="row align-items-center">


                    <div class="col-6 col-lg-2 float-left">
                        <a href="/">
                            <img src="~/img/logo-pequenina-clara.png" width="65">
                        </a>

                        <div class="col-2 col-lg-2 float-right">
                            <h1 class="mb-0 site-logo pt-3 mb-0 mt-2">
                                <a>
                                    USALE
                                </a>
                            </h1>
                        </div>
                    </div>

                    <div class="col-12 col-md-10 d-none d-lg-block">
                        <nav class="site-navigation position-relative text-right" role="navigation">




                            <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li>
                                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                    </li>
                                    <li>
                                        <a class="nav-link" asp-controller="Dashboard" asp-action="QrCode">QR Code</a>
                                    </li>
                                    <li>
                                        <a class="nav-link" asp-controller="Dashboard" asp-action="EditLoja">Edit Loja</a>
                                    </li>

                                    <li>
                                        @*TODO: DEIXAR COM UMA CLASSE PRA FICAR COM CURSOR POINTER*@
                                        <a asp-action="Logout" asp-controller="Home">
                                            Sair
                                        </a>
                                    </li>


                                }
                                else
                                {

                                    <li>
                                        <a class="nav-link" asp-controller="User" asp-action="ModalUserRegister">Registrar</a>
                                    </li>

                                    <li>
                                        <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Entrar</a>
                                    </li>
                                }


                            </ul>



                        </nav>
                    </div>


                    <div class="col-6 d-inline-block d-lg-none ml-md-0 py-3" style="position: relative; top: 3px;">

                        <a href="#" id="botao-navbar" class="burger site-menu-toggle js-menu-toggle active" data-toggle="collapse" data-target="#main-navbar">
                            <span></span>
                        </a>
                    </div>

                </div>
            </div>

        </header>
    </div>

    <style>
        #minha-navbar-lateral {
            position: fixed;
            top: -1000px;
            width: 100%;
            height: auto;
            background-color: #fff;
            z-index: 999;
        }

        #listinha-meu-menu-lateral {
            z-index: 1000;
            color: #fff;
        }
    </style>

    <div id="minha-navbar-lateral">
        <ul id="listinha-meu-menu-lateral">
            @if (SignInManager.IsSignedIn(User))
            {
                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    <a class="nav-link" asp-controller="Intra" asp-action="Index">Dashboard</a>
                </li>
                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    <a class="nav-link" asp-controller="Intra" asp-action="Index">QR Code</a>
                </li>
                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    <a class="nav-link" asp-controller="Intra" asp-action="Index">Edit Loja</a>
                </li>

                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    @*TODO: DEIXAR COM UMA CLASSE PRA FICAR COM CURSOR POINTER*@
                    <a asp-action="Logout" asp-controller="Home">
                        Sair
                    </a>
                </li>


            }
            else
            {

                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    <a class="nav-link" asp-controller="User" asp-action="ModalUserRegister">Registrar</a>
                </li>

                <li class="w-100 text-center text-light border-bottom border-light p-2">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Entrar</a>
                </li>
            }
        </ul>
    </div>




    @RenderBody()


    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/js/jquery-3.4.1-COMPLETASSO.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/vendor/sticky/sticky.js" type="text/javascript"></script>
    <script src="~/vendor/owlcarousel/owl.carousel.js" type="text/javascript"></script>
    <script src="~/vendor/aos/aos.js" type="text/javascript"></script>
    <script src="~/vendor/easing/easing.js" type="text/javascript"></script>

    <script src="~/js/main.js" type="text/javascript"></script>




    <script type="text/javascript">


        $(document).ready(function () {


            $("#btn-sair").click(function () {
                $("#logoutForm").submit();
            });


            var aberto = false;

            $("#botao-navbar").click(function () {

                if (aberto) {
                    $("#minha-navbar-lateral").css({ "top": "-1000px", "transition-duration": "300ms" });
                    aberto = false;
                }
                else {
                    $("#minha-navbar-lateral").css({ "top": "75px", "transition-duration": "300ms" });
                    aberto = true;
                }

            });


            var janela = $(window).width();

            var cont = 1;

            setInterval(function () {
                if (cont < 0) {
                    janela = $(window).width();
                    if (janela < 992) {
                        $('#minha-navbar-lateral').css('display', 'block');
                    } else {
                        $('#minha-navbar-lateral').css('display', 'none');
                    }
                    cont = 1;
                }
                cont--;

            }, 100);








        });

    </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="~/js/jquery-3.4.1-COMPLETASSO.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"></script>
    <script src="~/vendor/sticky/sticky.js" type="text/javascript"></script>
    <script src="~/vendor/owlcarousel/owl.carousel.js" type="text/javascript"></script>
    <script src="~/vendor/aos/aos.js" type="text/javascript"></script>
    <script src="~/vendor/easing/easing.js" type="text/javascript"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/jquery-funcoes.js"></script>
</body>


</html>